/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogsOption;

import autresClasses.BonAchat;
import autresClasses.ListeLot;
import autresClasses.Lot;
import autresClasses.Objet;
import autresClasses.PanneauImage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EventListener;
import javax.swing.*;

/**
 *
 * @author Abider
 */
public class AjoutLotDlg extends javax.swing.JDialog {

    private boolean valider;
    private Lot monlot;
    private Image img;
    private int somme;
    private JComboBox combo;
    private PanneauImage panImg;
    private boolean ok;

    public Lot getMonlot() {
        return monlot;
    }

    public boolean isValider() {
        return valider;
    }

    public void setValier(boolean valider) {
        this.valider = valider;
    }

    /**
     * Creates new form AjoutLotDlg
     */

    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        panImg = new PanneauImage();
        monlot = null;
        this.ok = false;
    }

    public boolean getOk() {
        return this.ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categorie = new javax.swing.ButtonGroup();
        niveau = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Photo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Descriptif = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        BonCadeau = new javax.swing.JRadioButton();
        Objet = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        Niv1 = new javax.swing.JRadioButton();
        Niv2 = new javax.swing.JRadioButton();
        Niv3 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        PanComboMontant = new javax.swing.JPanel();
        PanBParcourir = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Saisie d'un nouveau lot");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jPanel10.setLayout(new java.awt.GridLayout(3, 1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descriptif");
        jPanel10.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Catégorie");
        jPanel10.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Niveau");
        jPanel10.add(jLabel7);

        jPanel4.add(jPanel10);

        Photo.setLayout(new java.awt.GridLayout(1, 1));
        jPanel4.add(Photo);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));
        jPanel6.add(Descriptif);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        categorie.add(BonCadeau);
        BonCadeau.setText("Bon cadeau");
        BonCadeau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonCadeauActionPerformed(evt);
            }
        });
        jPanel8.add(BonCadeau);

        categorie.add(Objet);
        Objet.setSelected(true);
        Objet.setText("Objet");
        Objet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetActionPerformed(evt);
            }
        });
        jPanel8.add(Objet);

        jPanel6.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        niveau.add(Niv1);
        Niv1.setText("1");
        jPanel9.add(Niv1);

        niveau.add(Niv2);
        Niv2.setText("2");
        jPanel9.add(Niv2);

        niveau.add(Niv3);
        Niv3.setText("3");
        jPanel9.add(Niv3);

        jPanel6.add(jPanel9);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        PanComboMontant.setLayout(new java.awt.GridLayout(1, 1));
        jPanel7.add(PanComboMontant);

        PanBParcourir.setLayout(new java.awt.GridLayout(1, 1));
        jPanel7.add(PanBParcourir);

        jPanel5.add(jPanel7);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(BAnnuler);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        jPanel3.add(BValider);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BonCadeauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BonCadeauActionPerformed
        // TODO add your handling code here:
        this.PanComboMontant.removeAll();
        this.Photo.removeAll();
        this.PanBParcourir.removeAll();
        if (this.BonCadeau.isSelected()) {
            JComboBox ComboPrix = new JComboBox(); // déclaration et création d'une comboBox
            combo = ComboPrix;
            // abonnement de l'ecouteur
            ComboPrix.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ComboPrixActionPerformed(evt);
                }
            });

            ComboPrix.addItem(20); // remplissage de la combo avec le prix
            ComboPrix.addItem(30); // remplissage de la combo avec le prix
            ComboPrix.addItem(50); // remplissage de la combo avec le prix
            ComboPrix.addItem(100); // remplissage de la combo avec le prix
            ComboPrix.addItem(150); // remplissage de la combo avec le prix
            ComboPrix.addItem(200); // remplissage de la combo avec le prix
            ComboPrix.addItem(300); // remplissage de la combo avec le prix

            this.PanComboMontant.add(ComboPrix);// ajout de la combo au panel reservé

        }
        this.setSize(this.getWidth() + 1, this.getHeight() + 1);

    }// GEN-LAST:event_BonCadeauActionPerformed

    // gestionnaire d'évenement
    private void ComboPrixActionPerformed(ActionEvent evt) {
        somme = Integer.parseInt(this.combo.getSelectedItem().toString());

    }

    private void ObjetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ObjetActionPerformed
        // TODO add your handling code here:
        // on vide les panneau avant de faire des ajout
        this.PanComboMontant.removeAll();
        this.Photo.removeAll();
        this.PanBParcourir.removeAll();
        if (this.Objet.isSelected()) {
            this.Photo.add(this.panImg); // on ajoute le panneau qui affichera l'image
            panImg.setBackground(Color.white);
            JButton btParc = new JButton(); // creation du bouton parcourir
            btParc.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btParcActionPerformed(evt);
                }
            });
            btParc.setText("Parcourir");
            this.PanBParcourir.add(btParc); // ajout au panel reservé
        }
        this.setSize(this.getWidth() + 1, this.getHeight() + 1); // pour favorisé le rafraichissement de la fenêtre
    }// GEN-LAST:event_ObjetActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        int niv = 0;
        // on récupère le niveau
        if (this.Niv1.isSelected())
            niv = 1;
        if (this.Niv2.isSelected())
            niv = 2;

        if (this.Niv3.isSelected())
            niv = 3;

        if (this.Descriptif.getText().equals("")) { // on vérifi qu'il y a bien un descriptif
            this.Descriptif.setText("veillez entrez une description du cadeau");
        } else {

            if (this.BonCadeau.isSelected()) {// si c'est un bon d'achat

                monlot = new BonAchat(this.Descriptif.getText(), "Bon d'achat", niv, somme); // creation d'un lot de
                                                                                             // type bon D'achat
                this.ok = true;
                System.out.println(monlot);
            } else if (this.Objet.isSelected()) { // si c'est un objet
                this.img = this.panImg.getImg();
                monlot = new Objet(this.Descriptif.getText(), "Objet", niv, img);// creationd'un lot de type objet
                this.ok = true;
            }
            this.setVisible(false);
            this.dispose();
        }

    }// GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }// GEN-LAST:event_BAnnulerActionPerformed

    private void btParcActionPerformed(ActionEvent evt) {
        JFileChooser diag = new JFileChooser();
        if (diag.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String nfc = diag.getSelectedFile().getPath();
            this.img = Toolkit.getDefaultToolkit().getImage(nfc);
            this.panImg.setImg(img);
        }
        repaint();

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BValider;
    private javax.swing.JRadioButton BonCadeau;
    private javax.swing.JTextField Descriptif;
    private javax.swing.JRadioButton Niv1;
    private javax.swing.JRadioButton Niv2;
    private javax.swing.JRadioButton Niv3;
    private javax.swing.JRadioButton Objet;
    private javax.swing.JPanel PanBParcourir;
    private javax.swing.JPanel PanComboMontant;
    private javax.swing.JPanel Photo;
    private javax.swing.ButtonGroup categorie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.ButtonGroup niveau;
    // End of variables declaration//GEN-END:variables
}
