/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogsOption;

import autresClasses.ListeLot;
import autresClasses.Lot;
import autresClasses.Objet;
import autresClasses.PanneauImage;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Abider
 */
public class VisuLotsDlg extends javax.swing.JDialog {
    /**
     * Creates new form VisuLotsDlg
     */
    public VisuLotsDlg(java.awt.Frame parent, boolean modal, ListeLot lstl) {
        super(parent, modal);
        initComponents();
        initLot(lstl);
    }

    public void initLot(ListeLot lstL) {
        int taille = lstL.getLstL().size();
        this.PanPhotosLots.setLayout(new GridLayout((taille / 2) + 1, 2)); // affiche n line sur 2 colonne
        for (Lot l : lstL.getLstL()) {
            if (l.getCategorie().equals("Bon d'achat")) {
                JLabel lab = new JLabel(l.getDescriptif());
                this.PanPhotosLots.add(lab); // ajout du label
            } else {
                Objet obj = (Objet) l; // convertion de type lot en type Objet
                PanneauImage pan = new PanneauImage(obj.getPho()); // creation de pannel pour la photo avec le phot du
                                                                   // lot courant
                this.PanPhotosLots.add(pan);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanPhotosLots = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Photo des cadeaux à gagner");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanPhotosLotsLayout = new javax.swing.GroupLayout(PanPhotosLots);
        PanPhotosLots.setLayout(PanPhotosLotsLayout);
        PanPhotosLotsLayout.setHorizontalGroup(
                PanPhotosLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        PanPhotosLotsLayout.setVerticalGroup(
                PanPhotosLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 248, Short.MAX_VALUE));

        getContentPane().add(PanPhotosLots, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false); // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanPhotosLots;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
